# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

# [!] Build notice:
# Note that this installer curls the beaker linux binary. This
# will replaced with a verified installer soon.

name: setup beaker
author: carabiner-dev
description: 'Installs the Carabiner beaker attester into to the runner environment'
branding:
  icon: 'download-cloud'
  color: 'green'
inputs:
  install-dir:
    description: 'Path to install the binary'
    required: false
    default: '$HOME/.carabiner'
runs:
  using: "composite"
  steps:
      - name: Curl the beaker binary (tmp)
        shell: bash
        run: |
          mkdir -p ${{ inputs.install-dir }}/bin || :
          curl -Lo ${{ inputs.install-dir }}/bin/beaker https://github.com/carabiner-dev/beaker/releases/download/v0.1.1/beaker-v0.1.1-linux-amd64
          chmod 0755 ${{ inputs.install-dir }}/bin/beaker

      - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: echo "${{ inputs.install-dir }}/bin" >> $GITHUB_PATH
        shell: bash
      - if: ${{ runner.os == 'Windows' }}
        run: echo "${{ inputs.install-dir }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: bash
      
      - shell: bash
        run: beaker version
  