# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

# [!] Build notice:
# Note that this installer downloads bnd fromthe release page. This
# will replaced with a verified installer soon.

name: setup bnd
author: carabiner-dev
description: 'Installs the Carabiner bnd attester into to the runner environment'
branding:
  icon: 'download-cloud'
  color: 'green'
inputs:
  install-dir:
    description: 'Path to install the binary'
    required: false
    default: '$HOME/.carabiner'
runs:
  using: "composite"
  steps:
      - name: Install Linux Binary
        shell: bash
        run: |
          mkdir -p ${{ inputs.install-dir }}/bin || :
          curl -Lo ${{ inputs.install-dir }}/bin/bnd https://github.com/carabiner-dev/bnd/releases/download/v0.3.2/bnd-v0.3.2-linux-amd64
          chmod 0755 ${{ inputs.install-dir }}/bin/bnd

      - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: echo "${{ inputs.install-dir }}/bin" >> $GITHUB_PATH
        shell: bash
      - if: ${{ runner.os == 'Windows' }}
        run: echo "${{ inputs.install-dir }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: bash
      
      - shell: bash
        run: bnd version
  