# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

# [!] Build notice:
# Note that this installer downloads bnd fromthe release page. This
# will replaced with a verified installer soon.

name: setup bnd
author: carabiner-dev
description: 'Installs the Carabiner bnd attester into to the runner environment'
branding:
  icon: 'download-cloud'
  color: 'green'
inputs:
  install-dir:
    description: 'Path to install the binary'
    required: false
    default: '$HOME/.carabiner'
runs:
  using: "composite"
  steps:
    # - name: Drop bnd
    #   uses: carabiner-dev/actions/drop@HEAD
    #   with:
    #     insecure: true
    #     binary: carabiner-dev/bnd
    #     directory: ${{ inputs.install-dir }} 
      # - name: Checkout code
      #   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      #   with:
      #     persist-credentials: false
      #     repository: carabiner-dev/bnd
      #     path: '.build/bnd/'
      #     ref: main

      # - name: Set up Go
      #   uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      #   with:
      #     go-version-file: '.build/bnd/go.mod'
      #     cache: false
      #     check-latest: true

      - name: Install Linux Binary
        shell: bash
        run: |
          mkdir -p ${{ inputs.install-dir }}/bin || :
          curl -Lo ${{ inputs.install-dir }}/bin/bnd https://github.com/carabiner-dev/bnd/releases/download/v0.1.3/bnd-v0.1.3-linux-amd64
          chmod 0755 ${{ inputs.install-dir }}/bin/bnd

      - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: echo "${{ inputs.install-dir }}/bin" >> $GITHUB_PATH
        shell: bash
      - if: ${{ runner.os == 'Windows' }}
        run: echo "${{ inputs.install-dir }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: bash
      
      - shell: bash
        run: bnd version
  