# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0
---
name: 'Verify Policy'
author: "carabiner-dev"
description: 'Verifies a subject against a policy'
branding:
  icon: 'award'
  color: 'green'
inputs:
  policy:
    description: Don't attempt to find and apply security policies
    required: true
  subject:
    description: 'Path to a file or hash (algo:value) to use as verification subject'
    required: true
  collector:
    description: 'Collector to load to read attestations'
    required: true
  attest:
    description: 'Attest the policy evaluation results'
    required: false
    default: "true"
  push-attestation:
    description: 'Pushes the attestation to the GitHub attestations store'
    required: false
    default: "false"
  fail:
    description: 'Fail the workflow if the policy fails'
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: carabiner-dev/actions/install/ampel@HEAD
      name: 🔴🟡🟢 AMPEL Setup
      id: install

    - id: verify
      shell: bash
      run: |
        ampel verify \
          --subject="${{ inputs.subject }}" \
          --collector="${{ inputs.collector }}" \
          --policy="${{ inputs.policy }}" \
          --exit-code="${{ inputs.fail }}" \
          --attest-results="${{ inputs.attest }}" \
          --format="html" >> $GITHUB_STEP_SUMMARY

    - if: ${{ inputs.attest == 'true' }}
      name: Setup bnd
      uses: carabiner-dev/actions/install/bnd@HEAD

    - if: ${{ inputs.attest == 'true' }}
      name: sign-ampel-results
      shell: bash
      run: |
        bnd results.intoto.json >> ampel.bundle.json

    - if: ${{ inputs.attest == 'true' }}
      name: Push attestation to artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ampel.bundle.json
        path: ampel.bundle.json
