# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0
---
name: 'Verify Policy'
description: 'Verifies a subject against a policy'
inputs:
  policy:
    description: Don't attempt to find and apply security policies
    required: true
  subject:
    description: 'Path to a file or hash (algo:value) so use as subject'
    required: true
  collector:
    description: 'Collector to load to read attestations'
    default: '$HOME/.carabiner'
runs:
  using: composite
  steps:
    - name: Checkout code (drop)
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
          persist-credentials: false
      
    - uses: ./../../install/ampel
      name: 🔴🟡🟢 AMPEL Setup
      id: install

    - id: verify
      shell: bash
      run: |
        ampel verify \
          --subject="${{ inputs.subject }}" \
          --collector="${{ inputs.collectors }}" \
          --policy="${{ inputs.policy }}"
