# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0
---
name: 'Verify Policy'
author: "carabiner-dev"
description: 'Verifies a subject against a policy'
branding:
  icon: 'award'
  color: 'green'
inputs:
  policy:
    description: Don't attempt to find and apply security policies
    required: true
  subject:
    description: 'Path to a file or hash (algo:value) so use as subject'
    required: true
  collector:
    description: 'Collector to load to read attestations'
    default: '$HOME/.carabiner'
runs:
  using: composite
  steps:
    - uses: carabiner-dev/actions/install/ampel@HEAD
      name: 🔴🟡🟢 AMPEL Setup
      id: install

    - id: verify
      shell: bash
      run: |
        ampel verify \
          --subject="${{ inputs.subject }}" \
          --collector="${{ inputs.collectors }}" \
          --policy="${{ inputs.policy }}"
