# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0
---
name: 'Verify Policy'
author: "carabiner-dev"
description: 'Verifies a subject against a policy'
branding:
  icon: 'award'
  color: 'green'
inputs:
  policy:
    description: Don't attempt to find and apply security policies
    required: true
  subject:
    description: 'Path to a file or hash (algo:value) to use as verification subject'
    required: true
  collector:
    description: 'Collector to load to read attestations'
    required: true
  attest:
    description: 'Attest the policy evaluation results'
    required: false
    default: "true"
  attest-format:
    description: 'Format of the results attestation'
    required: false
    default: "ampel"
  results-path:
    description: "Path to store the results attestation"
    required: false
    default: "ampel.intoto.json"
  push-attestation:
    description: 'Pushes the attestation to the GitHub attestations store'
    required: false
    default: "false"
  attestation:
    description: 'Comma separated list of attestations to ingest'
    required: false
    default: ""
  signer:
    description: 'Comma separated list of signer identity slugs'
    required: false
    default: ""
  fail:
    description: 'Fail the workflow if the policy fails'
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: carabiner-dev/actions/install/ampel@905b73551f012e2c2396fc5860875e57a9ca881a
      name: 🔴🟡🟢 AMPEL Setup
      id: install

    - id: verify
      shell: bash
      run: |
        ampel verify \
          --subject="${{ inputs.subject }}" \
          --collector="${{ inputs.collector }}" \
          --policy="${{ inputs.policy }}" \
          --exit-code="${{ inputs.fail }}" \
          --attest-results="${{ inputs.attest }}" \
          --attest-format="${{ inputs.attest-format }}" \
          --results-path="${{ inputs.results-path }}" \
          --attestation="${{ inputs.attestation }}" \
          --signer="${{ inputs.signer }}" \
          --format="html" >> $GITHUB_STEP_SUMMARY

    - if: ${{ inputs.attest == 'true' }}
      name: Setup bnd
      uses: carabiner-dev/actions/install/bnd@905b73551f012e2c2396fc5860875e57a9ca881a

    - if: ${{ inputs.attest == 'true' }}
      name: sign-ampel-results
      shell: bash
      run: |
        mv ${{ inputs.results-path }} ${{ inputs.results-path }}.tmp
        bnd statement ${{ inputs.results-path }}.tmp >> ${{ inputs.results-path }}

    - if: ${{ inputs.attest == 'true' && inputs.push-attestation == 'true' }} 
      name: Push attestation to artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ampel.intoto.json
        path: ${{ inputs.results-path }}
