# SPDX-FileCopyrightText: Copyright 2026 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: setup revex
author: carabiner-dev
description: 'Installs the OpenVEX revex document fixer into the runner'
branding:
  icon: 'download-cloud'
  color: 'green'
inputs:
  install-dir:
    description: 'Path to install the binary'
    required: false
    default: '$HOME/.carabiner'
  version:
    description: 'revex version to install'
    required: false
    default: 'v0.0.2'
runs:
  using: "composite"
  steps:
    - uses: carabiner-dev/actions/install/download-and-verify@174f1c83779af3d3d7e451b7ead7ba824d0d2aa9 # v1.2.2
      with:
        tool: revex
        version: ${{ inputs.version }}
        install-dir: ${{ inputs.install-dir }}
